/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poeitem;

/**
 *
 * @author charl
 */
public enum Base {
    CLAW, DAGGER, WAND, ONE_HAND_SWORD, THRUSTING_ONE_HAND_SWORD, ONE_HAND_AXE, ONE_HAND_MACE, SCEPTRE,
    RUNE_DAGGER, BOW, STAFF, TWO_HAND_SWORD, TWO_HAND_AXE, TWO_HAND_MACE, FISHING_ROD, WARSTAFF, CRIMSON_JEWEL,
    VIRIDIAN_JEWEL, MURDEROUS_EYE_JEWEL, SEARCHING_EYE_JEWEL, GHASTLY_EYE_JEWEL, HYPNOTIC_EYE_JEWEL, LARGE_CLUSTER_JEWEL,
    MEDIUM_CLUSTER_JEWEL, SMALL_CLUSTER_JEWEL, AMULET, RING, UNSET_RING, BELT, GLOVES, BOOTS, BODY_ARMOUR, HELMET,
    QUIVER, SHIELD, FLASK, MAP, WATCHSTONE;
}
